print ("The mean for the Alcohol dataset is", df['Alcohol'].mean())
print ("The median for the Alcohol dataset is", df['Alcohol'].median())
print ("The range for the Alcohol dataset is", (max(df['Alcohol'])-min(df['Alcohol'])))
print ("The standard deviation for the Alcohol dataset is", df['Alcohol'].std())
print ("The variance for the Alcohol dataset is", df['Alcohol'].var())
print ("The mean for the Tobacco dataset is", df['Tobacco'].mean())
print ("The median for the Tobacco dataset is", df['Tobacco'].median())
print ("The range for the Tobacco dataset is", (max(df['Tobacco'])-min(df['Tobacco'])))
print ("The variance for the Tobacco dataset is", df['Tobacco'].var())
print ("The standard deviation for the Tobacco dataset is", df['Tobacco'].std())